version: '3.7'

services:
  ui:
    container_name: ui
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
    ports:
      - '3000:3000'
    command: sh -c "next build && next start"
    networks:
      - react-prisma

networks:
  react-prisma:
