version: '3.7'

services:
  react-prisma:
    container_name: react-prisma
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
    ports:
      - '3000:3000'
    command: sh -c "npm install && npm run start"
    networks:
      - react-prisma

networks:
  react-prisma:
