version: "3.9"

services:
  client:
    container_name: client
    working_dir: /app
    image: node:latest
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    networks:
      - express_app_network
    command: sh -c "yarn && yarn dev"

  mongo_db:
    container_name: mongo_db
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: test_db_name
    volumes:
      - ${PWD}/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "27017:27017"
    networks:
      - express_app_network

  mongo_express:
    container_name: mongo_express
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo_db:27017
    ports:
      - "8081:8081"
    depends_on:
      - mongo_db
    networks:
      - express_app_network

networks:
  express_app_network:
