version: '3.7'

services:
  next_ui:
    container_name: next_ui
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
    ports:
      - '3000:3000'
    command: sh -c "npm run dev"
    networks:
      - react-prisma

networks:
  react-prisma:
